name: TrenchKing
favicon: null
layout_spectrum: 0.4181915996596217
typography_spectrum: 0.837074737995863
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.4267577235586941
  lightness: 0.3985414421185851
  saturation: 0.5962305546272546
  rhythmicContrast: 0.9909234843216836
purpose: []
